import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

export const metadata = {
  title: "Eventoraa",
  description: "Generated by Eventoraa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-gradient-to-br from-gray-950 via-zinc-900 to-stone-900 text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {/* Header */}
          <main className="relative min-h-screen container mx-auto pt-40 md:pt-32">

            <div className="pointer-events-none absolute inset-0 z-10 overflow-hidden">
              <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl" />
              <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-600/20 rounded-full blur-3xl" />

            </div>

            <div className="relative z-10">
              {children}
            </div>

            {/* Footer */}
          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
